package:
  name: binaryclassifier
  version: "0.1"

source:
  path: .

requirements:
  build:
    - python
    - setuptools ==27.2.0

  run:
    - python
    - pycli

test:
  requires:
    - nose

  files:
    - binaryclassifier
    - tests/test_main.py

about:
  home: https://github.com/CSC380Team8/binary-classifier
  license: GPLv3
  license_file: LICENSE
